package:
  name: ballcools
  version: "0.0.3"

source:
  path: ../
  #path: file.tar.gz
  #url: http://neomorph.salk.edu/wtian/share/file.tar.gz
  #url: https://github.com/username/my_cpp_package/archive/v1.0.tar.gz
  #sha256: put_the_sha256_of_your_tarball_here

build:
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - make
    - zlib
    - bzip2
    - htslib>=1.10
    - libdeflate
  host:
    - zlib
    - bzip2
    - htslib>=1.10
    - libdeflate
  run:
    - zlib
    - bzip2
    - htslib>=1.10
    - libdeflate
    - tabix

test:
  commands:
    - ballcools --help

about:
  home: https://github.com/jksr/ballcools
  license: GNU General Public License v2.0 (https://github.com/jksr/ballcools/blob/main/LICENSE)
  summary: BAllCools (tools for binary file format of DNA methylation data)

