g++ -w -O3 -c allc.cc             -I htslib/htslib  -std=c++11 -o out/allc.o
g++ -w -O3 -c hashtable.cc        -I htslib/htslib  -std=c++11 -o out/hashtable.o
g++ -w -O3 -c ballc.cc            -I htslib/htslib  -std=c++11 -o out/ballc.o
g++ -w -O3 -c ballc_index.cc      -I htslib/htslib  -std=c++11 -o out/ballc_index.o
g++ -w -O3 -c ballc_index_core.cc -I htslib/htslib  -std=c++11 -o out/ballc_index_core.o
g++ -w -O3 -c utils.cc            -I htslib/htslib  -std=c++11 -o out/utils.o
g++ -w -O3 -c timer.cc            -I htslib/htslib  -std=c++11 -o out/timer.o
g++ -w -O3 out/*.o htslib/libhts.a libdeflate/libdeflate.a main_allc2ballc.cc -I htslib/htslib  -std=c++11  -lz -pthread  -o out/allc2ballc.out
g++ -w -O3 out/*.o  htslib/libhts.a  main_allc2ballc.cc -I htslib/htslib  -std=c++11  -L /data/wtian/local/miniconda3/envs/sapiens/lib -ldeflate -lz -pthread  -o out/allc2ballc.out2
#g++ -w -O3 out/*.o main_checkballc.cc -I /data/wtian/local/miniconda3/envs/sapiens/include -L /data/wtian/local/miniconda3/envs/sapiens/lib -lhts -ldeflate -lbz2 -std=c++11 -lz -o out/checkballc.out
#g++ -w -O3 out/*.o main_indexballc.c -I /data/wtian/local/miniconda3/envs/sapiens/include -L /data/wtian/local/miniconda3/envs/sapiens/lib -lhts -ldeflate -lbz2 -std=c++11 -lz -o out/indexballc.out
#g++ -w -O3 out/*.o main_queryballc.c -I /data/wtian/local/miniconda3/envs/sapiens/include -L /data/wtian/local/miniconda3/envs/sapiens/lib -lhts -ldeflate -lbz2 -std=c++11 -lz -o out/queryballc.out
#g++ -w -O3 out/*.o main_queryboth.cc -I /data/wtian/local/miniconda3/envs/sapiens/include -L /data/wtian/local/miniconda3/envs/sapiens/lib -lhts -ldeflate -lbz2 -std=c++11 -lz -o out/queryboth.out
